FROM node:18

ARG buildStage
ARG dockerport=3000
ENV BUILD_STAGE $buildStage
ENV DOCKER_PORT $dockerport

RUN mkdir /Project
COPY . /Project
WORKDIR /Project

RUN npm i
RUN sed -i 's/\r$//' run-dev.bash

EXPOSE $dockerport
