### register
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "username":"admin1",
    "password":"1234"
}


### getuser
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "email":"sudtae54@gmail.com",
    "phone":"0887888887"
}

### healthcheck
GET http://localhost:9777/healthcheck HTTP/1.1
Content-Type: application/json