### register
POST http://localhost:9777/order/payment HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJleHAiOjE2OTQwMjk1OTgsImlhdCI6MTY5MzAyOTU5OH0.LUQ3f8Lomz6AHi6I7If1imFErya2aIGorJRudW9olKk

{
    "orderId":1,
    "full_paid":true
}


### getuser
POST http://localhost:9777/user HTTP/1.1
Content-Type: application/json

{
    "email":"sudtae54@gmail.com",
    "phone":"0887888887"
}

### healthcheck
POST http://localhost:3000/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJleHAiOjE2OTQwMjk1OTgsImlhdCI6MTY5MzAyOTU5OH0.LUQ3f8Lomz6AHi6I7If1imFErya2aIGorJRudW9olKk

{
    "originCountry": "TH",
    "destinationCountry": "BKK",
    "startDate": "2023-08-24",
    "endDate": "2023-08-29",
    "package": {
        "packageName": "ECONOMY",
        "packagePrice": {
            "value": "180",
            "unit": "Baht"
        },
        "coverages": [
            {
                "title": "Personal Accident Loss of Life, Dismemberment, Loss of Sight or Total Permanent Disability",
                "detail": {
                    "value": "1000000",
                    "unit": "Baht"
                }
            },
            {
                "title": "Medical Expense due to Accident and Illnesses including COVID-19",
                "detail": {
                    "value": "500000",
                    "unit": "Baht"
                }
            },
            {
                "title": "Emergency Medical Evacuation and Repatriation",
                "detail": {
                    "value": "1000000",
                    "unit": "Baht"
                }
            },
            {
                "title": "Repatriation of Mortal Remains",
                "detail": {
                    "value": "1000000",
                    "unit": "Baht"
                }
            },
            {
                "title": "Trip Cancellation (Before Trip Starts due to Specified Caused)",
                "detail": {
                    "value": "N/A",
                    "unit": "Baht"
                }
            },
            {
                "title": "Third Party Liability",
                "detail": {
                    "value": "1000000",
                    "unit": "Baht"
                }
            },
            {
                "title": "Travel Delay (Every 8 Hours / 1,000 Baht due to Specified Caused)",
                "detail": {
                    "value": "10000",
                    "unit": "Baht"
                }
            },
            {
                "title": "Flight Misconnection (Every 8 Hours / 1,000 Baht)",
                "detail": {
                    "value": "3000",
                    "unit": "Baht"
                }
            },
            {
                "title": "Trip Curtailment (Due To Specified Caused)",
                "detail": {
                    "value": "N/A",
                    "unit": "Baht"
                }
            },
            {
                "title": "Baggage Delay (Every 8 Hours / 1,000 Baht)",
                "detail": {
                    "value": "N/A",
                    "unit": "Baht"
                }
            },
            {
                "title": "Loss or Damage of Suitcase / Personal Effects while Suitcase and Personal Effects is in Care Custody and Control of the Hotels Staff or Carrier or arising from Robbery, Gang-Robbery or Way of Violent Mean",
                "detail": {
                    "value": "5000",
                    "unit": "Baht"
                }
            },
            {
                "title": "Loss or Damage of Personal Money and Travel Cheque arising from Robbery, Gang-Robbery or Way of Violent Mean",
                "detail": {
                    "value": "N/A",
                    "unit": "Baht"
                }
            },
            {
                "title": "Loss or Damage of Travel Documents arising from Robbery, Gang-Robbery or Way of Violent Mean",
                "detail": {
                    "value": "N/A",
                    "unit": "Baht"
                }
            },
            {
                "title": "Hospital Income Benefit (Maximum 20 days)",
                "detail": {
                    "value": "N/A",
                    "unit": "Baht"
                }
            }
        ]
    }
}